/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session State
         * @description Return the authoritative session snapshot for full resync.
         *
         *     Called by the frontend when the WS event bus sends ``client.resync_required``
         *     (i.e. the requested replay window is no longer available).
         *
         *     See ``docs/api.md`` §3 and §4.
         */
        get: operations["get_session_state_v1_sessions__session_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Models */
        get: operations["get_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Model */
        post: operations["select_model_v1_models_select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssistantStateData */
        AssistantStateData: {
            /** State */
            state: string;
            /** Intensity */
            intensity: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModelSelectionReq */
        ModelSelectionReq: {
            /** Role */
            role: string;
            /** Model Id */
            model_id: string;
        };
        /**
         * SessionStateResponse
         * @description Authoritative session snapshot returned by GET /v1/sessions/{id}/state.
         *
         *     Used by the frontend to fully resync after a replay gap.
         *     See ``docs/api.md`` §3 and the ``client.resync_required`` WS event.
         */
        SessionStateResponse: {
            /** Session Id */
            session_id: string;
            /** Last Seq */
            last_seq: number;
            assistant_state: components["schemas"]["AssistantStateData"];
            /** Active Run */
            active_run?: string | null;
            /** Pending Approvals */
            pending_approvals?: unknown[];
            /** Active Task */
            active_task?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** AgentDeltaData */
        AgentDeltaData: {
            /** Channel */
            channel: string;
            /** Text */
            text: string;
        };
        /** AgentErrorData */
        AgentErrorData: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Recoverable */
            recoverable: boolean;
            /**
             * Correlation Id
             * @default null
             */
            correlation_id: string | null;
        };
        /** AgentMessageData */
        AgentMessageData: {
            /** Message Id */
            message_id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Finish Reason */
            finish_reason: string;
            /** Steps Used */
            steps_used: number;
            /** Tokens */
            tokens: {
                [key: string]: number;
            };
            /**
             * Incomplete
             * @default false
             */
            incomplete: boolean | null;
        };
        /** ChatSendData */
        ChatSendData: {
            /** Session Id */
            session_id: string;
            /** Text */
            text: string;
            /**
             * Client Msg Id
             * @default null
             */
            client_msg_id: string | null;
        };
        /** RunCancelData */
        RunCancelData: {
            /** Run Id */
            run_id: string;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
        };
        /** SessionReadyData */
        SessionReadyData: {
            /** Last Seq */
            last_seq: number;
            assistant_state: components["schemas"]["AssistantStateData"];
            /** Model */
            model: {
                [key: string]: unknown;
            };
            /** Pending Approvals */
            pending_approvals: unknown[];
        };
        /** SystemEchoData */
        SystemEchoData: {
            /** Echoed Text */
            echoed_text: string;
        };
        /** WSEnvelope */
        WSEnvelope: {
            /**
             * V
             * @default 1
             */
            v: number;
            /**
             * Seq
             * @default null
             */
            seq: number | null;
            /** Ts */
            ts: string;
            /** Type */
            type: string;
            /** Session Id */
            session_id: string;
            /**
             * Run Id
             * @default null
             */
            run_id: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_session_state_v1_sessions__session_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    select_model_v1_models_select_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelSelectionReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
