/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentDeltaData */
        AgentDeltaData: {
            /** Channel */
            channel: string;
            /** Text */
            text: string;
        };
        /** AgentErrorData */
        AgentErrorData: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Recoverable */
            recoverable: boolean;
            /**
             * Correlation Id
             * @default null
             */
            correlation_id: string | null;
        };
        /** AgentMessageData */
        AgentMessageData: {
            /** Message Id */
            message_id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Finish Reason */
            finish_reason: string;
            /** Steps Used */
            steps_used: number;
            /** Tokens */
            tokens: {
                [key: string]: number;
            };
            /**
             * Incomplete
             * @default false
             */
            incomplete: boolean | null;
        };
        /** AssistantStateData */
        AssistantStateData: {
            /** State */
            state: string;
            /** Intensity */
            intensity: number;
        };
        /** SessionReadyData */
        SessionReadyData: {
            /** Last Seq */
            last_seq: number;
            assistant_state: components["schemas"]["AssistantStateData"];
            /** Model */
            model: {
                [key: string]: unknown;
            };
            /** Pending Approvals */
            pending_approvals: unknown[];
        };
        /** SystemEchoData */
        SystemEchoData: {
            /** Echoed Text */
            echoed_text: string;
        };
        /** WSEnvelope */
        WSEnvelope: {
            /**
             * V
             * @default 1
             */
            v: number;
            /**
             * Seq
             * @default null
             */
            seq: number | null;
            /** Ts */
            ts: string;
            /** Type */
            type: string;
            /** Session Id */
            session_id: string;
            /**
             * Run Id
             * @default null
             */
            run_id: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
