/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_v1_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session State
         * @description Return the authoritative session snapshot for full resync.
         *
         *     Called by the frontend when the WS event bus sends ``client.resync_required``
         *     (i.e. the requested replay window is no longer available).
         *
         *     See ``docs/api.md`` §3 and §4.
         */
        get: operations["get_session_state_v1_sessions__session_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Models */
        get: operations["get_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Model */
        post: operations["select_model_v1_models_select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Approvals */
        get: operations["list_approvals_v1_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Respond Approval */
        post: operations["respond_approval_v1_approvals__approval_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Grants */
        get: operations["list_grants_v1_grants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/grants/{grant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Grant */
        delete: operations["revoke_grant_v1_grants__grant_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/fs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fs Settings */
        get: operations["get_fs_settings_v1_settings_fs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/fs/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Fs Root */
        post: operations["add_fs_root_v1_settings_fs_roots_post"];
        /** Remove Fs Root */
        delete: operations["remove_fs_root_v1_settings_fs_roots_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddRootReq */
        AddRootReq: {
            /** Root */
            root: string;
            /**
             * Confirm Risk
             * @default false
             */
            confirm_risk: boolean;
        };
        /** ApprovalResponseReq */
        ApprovalResponseReq: {
            /** Action */
            action: string;
            /**
             * Scope
             * @default once
             */
            scope: string;
        };
        /** AssistantStateData */
        AssistantStateData: {
            /** State */
            state: string;
            /** Intensity */
            intensity: number;
            /**
             * Progress
             * @default null
             */
            progress: number | null;
            /**
             * Detail
             * @default null
             */
            detail: string | null;
            /**
             * Run Id
             * @default null
             */
            run_id: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModelSelectionReq */
        ModelSelectionReq: {
            /** Role */
            role: string;
            /** Model Id */
            model_id: string;
        };
        /** RemoveRootReq */
        RemoveRootReq: {
            /** Root */
            root: string;
        };
        /**
         * SessionStateResponse
         * @description Authoritative session snapshot returned by GET /v1/sessions/{id}/state.
         *
         *     Used by the frontend to fully resync after a replay gap.
         *     See ``docs/api.md`` §3 and the ``client.resync_required`` WS event.
         */
        SessionStateResponse: {
            /** Session Id */
            session_id: string;
            /** Last Seq */
            last_seq: number;
            assistant_state: components["schemas"]["AssistantStateData"];
            /** Active Run */
            active_run?: string | null;
            /** Pending Approvals */
            pending_approvals?: unknown[];
            /** Active Task */
            active_task?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** AgentDeltaData */
        AgentDeltaData: {
            /** Channel */
            channel: string;
            /** Text */
            text: string;
        };
        /** AgentErrorData */
        AgentErrorData: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Recoverable */
            recoverable: boolean;
            /**
             * Correlation Id
             * @default null
             */
            correlation_id: string | null;
        };
        /** AgentMessageData */
        AgentMessageData: {
            /** Message Id */
            message_id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Finish Reason */
            finish_reason: string;
            /** Steps Used */
            steps_used: number;
            /** Tokens */
            tokens: {
                [key: string]: number;
            };
            /**
             * Incomplete
             * @default false
             */
            incomplete: boolean | null;
        };
        /** ApprovalRequestedData */
        ApprovalRequestedData: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Tool Name */
            tool_name: string;
            /** Action Text */
            action_text: string;
            /** Targets */
            targets: string[];
            /** Risk */
            risk: string;
            /** Batch Count */
            batch_count: number;
        };
        /** ApprovalResolvedData */
        ApprovalResolvedData: {
            /** Id */
            id: string;
            /** Decision */
            decision: string;
        };
        /** ChatSendData */
        ChatSendData: {
            /** Session Id */
            session_id: string;
            /** Text */
            text: string;
            /**
             * Client Msg Id
             * @default null
             */
            client_msg_id: string | null;
        };
        /** RunCancelData */
        RunCancelData: {
            /** Run Id */
            run_id: string;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
        };
        /** SessionReadyData */
        SessionReadyData: {
            /** Last Seq */
            last_seq: number;
            assistant_state: components["schemas"]["AssistantStateData"];
            /** Model */
            model: {
                [key: string]: unknown;
            };
            /** Pending Approvals */
            pending_approvals: unknown[];
        };
        /** SystemEchoData */
        SystemEchoData: {
            /** Echoed Text */
            echoed_text: string;
        };
        /** ToolDecisionData */
        ToolDecisionData: {
            /** Call Id */
            call_id: string;
            /** Decision */
            decision: string;
            /** Rule Id */
            rule_id: string;
            /** Reason */
            reason: string;
        };
        /** ToolProgressData */
        ToolProgressData: {
            /** Call Id */
            call_id: string;
            /** Progress */
            progress: number;
        };
        /** ToolRequestedData */
        ToolRequestedData: {
            /** Call Id */
            call_id: string;
            /** Tool */
            tool: string;
            /** Category */
            category: string;
            /** Risk */
            risk: string;
            /** Args Preview */
            args_preview: string;
            /** Targets */
            targets: string[];
            /** Item Count */
            item_count: number;
            /** Taint */
            taint: boolean;
        };
        /** ToolResultData */
        ToolResultData: {
            /** Call Id */
            call_id: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Result Id */
            result_id: string;
            /** Duration Ms */
            duration_ms: number;
            /** Truncated */
            truncated: boolean;
            /** Undo Available */
            undo_available: boolean;
            /**
             * Error Code
             * @default null
             */
            error_code: string | null;
        };
        /** ToolStartedData */
        ToolStartedData: {
            /** Call Id */
            call_id: string;
        };
        /** WSEnvelope */
        WSEnvelope: {
            /**
             * V
             * @default 1
             */
            v: number;
            /**
             * Seq
             * @default null
             */
            seq: number | null;
            /** Ts */
            ts: string;
            /** Type */
            type: string;
            /** Session Id */
            session_id: string;
            /**
             * Run Id
             * @default null
             */
            run_id: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_sessions_v1_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_session_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_state_v1_sessions__session_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    select_model_v1_models_select_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelSelectionReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_approvals_v1_approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    respond_approval_v1_approvals__approval_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalResponseReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_grants_v1_grants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    revoke_grant_v1_grants__grant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fs_settings_v1_settings_fs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    add_fs_root_v1_settings_fs_roots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRootReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_fs_root_v1_settings_fs_roots_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveRootReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
