"""Approval lifecycle — server-issued, single-use, bound to the exact operation.

``docs/api.md`` §6 and ``docs/security.md`` §6 ("Approval spoofing", "TOCTOU on
approval"):

* the id is a server-issued nonce; the frontend cannot invent one;
* it is bound to ``(run_id, tool_name, sha256(canonical_args))``;
* it is single-use — a second response, or a response after consumption, is
  rejected and audited;
* it expires (default 120 s) and a timeout is treated as a denial;
* ``action_text`` is generated by the backend from validated arguments and is a
  distinct field from ``model_rationale``.  That separation is a security
  control, not a convenience.
"""

from __future__ import annotations

import asyncio
import json
import secrets
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any, Awaitable, Callable, Literal, Optional

from ..obs.logging import get_logger
from ..storage.database import Database

log = get_logger("policy.approvals")

#: ``docs/security.md`` §8: approval timeout default.
APPROVAL_TIMEOUT_S: float = 120.0

Outcome = Literal["allowed", "denied", "timeout"]
ScopeChoice = Literal["once", "session", "1h", "always"]

ALL_SCOPES: tuple[ScopeChoice, ...] = ("once", "session", "1h", "always")


class ApprovalError(RuntimeError):
    """The approval response is unknown, stale, replayed or mismatched."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code


@dataclass(slots=True)
class ApprovalRequest:
    """One pending approval."""

    id: str
    run_id: str
    session_id: str
    call_id: Optional[str]
    tool_name: str
    args_hash: str
    risk: str
    title: str
    action_text: str
    targets: list[str]
    item_count: int
    total_bytes: Optional[int]
    reversible: bool
    destructive: bool
    model_rationale: str
    scope_options: list[str]
    created_at: datetime
    expires_at: datetime
    event: asyncio.Event = field(default_factory=asyncio.Event, repr=False)
    outcome: Optional[Outcome] = None
    scope: Optional[str] = None
    consumed: bool = False

    def to_event(self) -> dict[str, Any]:
        return {
            "approval_id": self.id,
            "call_id": self.call_id,
            "task_id": None,
            "title": self.title,
            "action_text": self.action_text,
            "targets": list(self.targets),
            "item_count": self.item_count,
            "total_bytes": self.total_bytes,
            "risk": self.risk,
            "reversible": self.reversible,
            "destructive": self.destructive,
            "model_rationale": self.model_rationale,
            "scope_options": list(self.scope_options),
            "expires_at": self.expires_at.isoformat(),
        }

    def is_expired(self, now: datetime | None = None) -> bool:
        return (now or datetime.now(timezone.utc)) >= self.expires_at


class ApprovalManager:
    """Registry of pending approvals, optionally persisted for resync."""

    def __init__(self, db: Database | None = None, *, timeout_s: float = APPROVAL_TIMEOUT_S) -> None:
        self.db = db
        self.timeout_s = timeout_s
        self._pending: dict[str, ApprovalRequest] = {}
        self._history: dict[str, ApprovalRequest] = {}

    # -- creation -----------------------------------------------------------

    async def create(
        self,
        *,
        run_id: str,
        session_id: str,
        call_id: str | None,
        tool_name: str,
        args_hash: str,
        risk: str,
        title: str,
        action_text: str,
        targets: list[str],
        item_count: int,
        total_bytes: int | None,
        reversible: bool,
        destructive: bool,
        model_rationale: str,
        scope_options: list[str],
    ) -> ApprovalRequest:
        now = datetime.now(timezone.utc)
        request = ApprovalRequest(
            id=f"ap_{secrets.token_urlsafe(18)}",
            run_id=run_id,
            session_id=session_id,
            call_id=call_id,
            tool_name=tool_name,
            args_hash=args_hash,
            risk=risk,
            title=title,
            action_text=action_text,
            targets=targets,
            item_count=item_count,
            total_bytes=total_bytes,
            reversible=reversible,
            destructive=destructive,
            model_rationale=model_rationale,
            scope_options=scope_options,
            created_at=now,
            expires_at=now + timedelta(seconds=self.timeout_s),
        )
        self._pending[request.id] = request
        if self.db is not None:
            await self.db.execute_write(
                "INSERT INTO approvals (id, run_id, session_id, call_id, task_id, "
                "tool_name, args_hash, risk, action_text, targets_json, item_count, "
                "total_bytes, reversible, created_at, expires_at) "
                "VALUES (?, ?, ?, ?, NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    request.id,
                    run_id,
                    session_id,
                    call_id,
                    tool_name,
                    args_hash,
                    risk,
                    action_text,
                    json.dumps(targets, ensure_ascii=False),
                    item_count,
                    total_bytes,
                    1 if reversible else 0,
                    now.isoformat(),
                    request.expires_at.isoformat(),
                ),
            )
        return request

    # -- resolution ---------------------------------------------------------

    async def respond(
        self,
        approval_id: str,
        outcome: str,
        scope: str | None = None,
    ) -> ApprovalRequest:
        """Record a human decision.  Rejects unknown/stale/replayed responses."""
        request = self._pending.get(approval_id)
        if request is None:
            if approval_id in self._history:
                raise ApprovalError("APPROVAL_REPLAY", "This approval was already resolved.")
            raise ApprovalError("APPROVAL_UNKNOWN", "Unknown approval id.")
        if request.outcome is not None:
            raise ApprovalError("APPROVAL_REPLAY", "This approval was already resolved.")
        if request.is_expired():
            await self._finalize(request, "timeout", None)
            raise ApprovalError("APPROVAL_TIMEOUT", "This approval expired.")
        normalized = "allowed" if outcome in ("allow", "allowed") else "denied"
        if scope is not None and scope not in ALL_SCOPES:
            raise ApprovalError("APPROVAL_BAD_SCOPE", f"Unknown scope '{scope}'.")
        if normalized == "allowed" and scope is not None and scope not in request.scope_options:
            raise ApprovalError(
                "APPROVAL_BAD_SCOPE", f"Scope '{scope}' is not offered for this action."
            )
        await self._finalize(request, normalized, scope)
        return request

    async def expire(self, approval_id: str) -> ApprovalRequest | None:
        request = self._pending.get(approval_id)
        if request is None or request.outcome is not None:
            return None
        await self._finalize(request, "timeout", None)
        return request

    async def _finalize(self, request: ApprovalRequest, outcome: Outcome, scope: str | None) -> None:
        request.outcome = outcome
        request.scope = scope
        request.event.set()
        self._pending.pop(request.id, None)
        self._history[request.id] = request
        if self.db is not None:
            await self.db.execute_write(
                "UPDATE approvals SET resolved_at = ?, outcome = ?, scope = ? WHERE id = ?",
                (datetime.now(timezone.utc).isoformat(), outcome, scope, request.id),
            )

    # -- waiting ------------------------------------------------------------

    async def wait(self, request: ApprovalRequest) -> ApprovalRequest:
        """Block until resolved or the timeout elapses (timeout = denial)."""
        remaining = (request.expires_at - datetime.now(timezone.utc)).total_seconds()
        try:
            await asyncio.wait_for(request.event.wait(), timeout=max(0.0, remaining))
        except asyncio.TimeoutError:
            await self._finalize(request, "timeout", None)
        return request

    # -- consumption --------------------------------------------------------

    async def consume(self, approval_id: str, *, tool_name: str, args_hash: str) -> ApprovalRequest:
        """Single-use redemption immediately before authorization is minted."""
        request = self._history.get(approval_id) or self._pending.get(approval_id)
        if request is None:
            raise ApprovalError("APPROVAL_UNKNOWN", "Unknown approval id.")
        if request.consumed:
            raise ApprovalError("APPROVAL_REPLAY", "This approval was already used.")
        if request.outcome != "allowed":
            raise ApprovalError("APPROVAL_NOT_ALLOWED", "This approval was not granted.")
        if request.tool_name != tool_name:
            raise ApprovalError("APPROVAL_TOOL_MISMATCH", "The tool changed after approval.")
        if request.args_hash != args_hash:
            raise ApprovalError(
                "APPROVAL_ARGS_MISMATCH", "The arguments changed after approval."
            )
        if request.is_expired():
            raise ApprovalError("APPROVAL_TIMEOUT", "This approval expired before use.")
        request.consumed = True
        if self.db is not None:
            await self.db.execute_write(
                "UPDATE approvals SET consumed_at = ? WHERE id = ?",
                (datetime.now(timezone.utc).isoformat(), approval_id),
            )
        return request

    # -- introspection ------------------------------------------------------

    def pending(self, session_id: str | None = None) -> list[ApprovalRequest]:
        now = datetime.now(timezone.utc)
        return [
            request
            for request in self._pending.values()
            if not request.is_expired(now)
            and (session_id is None or request.session_id == session_id)
        ]

    def get(self, approval_id: str) -> ApprovalRequest | None:
        return self._pending.get(approval_id) or self._history.get(approval_id)


def scope_options_for(*, destructive: bool, reversible: bool, persistent_allowed: bool) -> list[str]:
    """Offered scopes.  ``always`` is never offered for destructive actions."""
    options: list[str] = ["once", "session", "1h"]
    if persistent_allowed and not destructive:
        options.append("always")
    return options


def scope_to_ttl(scope: str | None) -> tuple[float | None, bool]:
    """Map a scope choice to ``(ttl_seconds, session_bound)``."""
    if scope == "session":
        return None, True
    if scope == "1h":
        return 3600.0, False
    if scope == "always":
        return None, False
    return 0.0, False  # "once" creates no grant at all


__all__ = [
    "ALL_SCOPES",
    "APPROVAL_TIMEOUT_S",
    "ApprovalError",
    "ApprovalManager",
    "ApprovalRequest",
    "scope_options_for",
    "scope_to_ttl",
]
